---
- hosts: all
  become: True
  gather_facts: yes
  ignore_errors: 1

  #become_user: root

  tasks:
      - name: Create a file
        file:
          path: /tmp/playbookfile
          mode: '0755'
          state: touch
        tags:
           - file  
      - name: check something
        command: hlkkgyfuyi 
        tags:
           - cmd 
        

      - name: Create a directory
        file:
          path: /tmp/dir 
          mode: '0700'  
          state: directory
        tags:
           - dir   
      - name: Create group
        group:
          name: security
          state: present

      - name: Create user Dammy  
        user:
          comment: Dammy Admin
          shell: /bin/bash
          group: security
          name: Dammy
        when: ansible_os_family == "Debian" or ansible_processor_nproc > 2 
      - name: check uptime
        command: uptime
      - name: check the date
        shell: cat /etc/passwd | grep dammy  

          


        